let img;
let img_0;
let img_1;
let img_2;
let img_3;
let img_4;
let img_5;
let img_6;
let img_7;
let img_8;
let img_9;
let num_0;
let num_1;
let num_2;
let num_3;
let num_4;
let num_5;
let num_6;
let num_7;
let num_8;
let num_9;
let img_right;
let img_left;
let img_up;
let img_down;
let img_back;
let img_forward;
// starting digit
var digitToShow = 4;
function setup() {
    createCanvas(window.innerWidth, window.innerHeight);
    img = loadImage('https://i.postimg.cc/mrBhxRm7/IMG-0841.jpg');
    img_0 = loadImage('https://i.postimg.cc/Sxz6WbfL/0-pic.jpg');
    img_1 = loadImage('https://i.postimg.cc/kXR6HFRq/1-pic.jpg');
    img_2 = loadImage('https://i.postimg.cc/Jn0VfdZ1/img-2.jpg');
    img_3 = loadImage('https://i.postimg.cc/qqCfRh1S/img-3.jpg');
    img_4 = loadImage('https://i.postimg.cc/Qtz2vF0P/img-4.jpg');
    img_5 = loadImage('https://i.postimg.cc/0jJTv94N/img-5.jpg');
    img_6 = loadImage('https://i.postimg.cc/BZ8tDmk9/img-6.jpg');
    img_7 = loadImage('https://i.postimg.cc/QdDM2hth/img-7.jpg');
    img_8 = loadImage('https://i.postimg.cc/QM4xK7qd/img-8.jpg');
    img_9 = loadImage('https://i.postimg.cc/Kcgv4R3m/img-9.jpg');

    num_0 = loadImage('https://i.postimg.cc/CL3PCMNC/0-a4.jpg');
    num_1 = loadImage('https://i.postimg.cc/fbK8hch5/1-a4.jpg');
    num_2 = loadImage('https://i.postimg.cc/fT95bnNV/2-a4.jpg');
    num_3 = loadImage('https://i.postimg.cc/W1mnMGtj/3-a4.jpg');
    num_4 = loadImage('https://i.postimg.cc/Jh1QKsBX/4-a4.jpg');
    num_5 = loadImage('https://i.postimg.cc/gJ7qY4ty/5-a4.jpg');
    num_6 = loadImage('https://i.postimg.cc/vT67D9CJ/6-a4.jpg');
    num_7 = loadImage('https://i.postimg.cc/sfBb5Lzr/7-a4.jpg');
    num_8 = loadImage('https://i.postimg.cc/2jPMGxjB/8-a4.jpg');
    num_9 = loadImage('https://i.postimg.cc/sD78NZ1H/9-a4.jpg');

    img_right = loadImage('https://i.postimg.cc/4ySr1B05/Arrow-Right.jpg');
    img_left = loadImage('https://i.postimg.cc/tTrfXB9j/Arrow-Left.jpg');
    img_up = loadImage('https://i.postimg.cc/yNsrcMdK/ArrowUp.jpg');
    img_down = loadImage('https://i.postimg.cc/y6b5tpfh/Arrow-Down.jpg');
    img_back = loadImage('https://i.postimg.cc/Zn7kJg98/Arrow-Backward.jpg');
    img_forward = loadImage('https://i.postimg.cc/SRBgs55w/Arrow-Forward.jpg');
}